<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements Form_alter.
 */
function siteapikey_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	$data = \Drupal::state()->get('siteapikey') ? \Drupal::state()->get('siteapikey') : 'No API Key yet';
	$button_value = \Drupal::state()->get('siteapikey') ? 'Update configuration' : 'Save configuration';
  if($form['#form_id'] == 'system_site_information_settings'){
      $form['site_api_key'] = array(
        '#type' => 'textfield',
        '#title' => t('Site API key'),
        '#default_value' => $data,
    );
    /* Add a custom submit handler */
    $form['actions']['submit']['#value'] = $button_value;
    $form['#submit'][] = 'siteapikey_custom_submit';
  }
}

/**
 * Make the form submit handler.
 */
function siteapikey_custom_submit($form, FormStateInterface $form_state) {
  \Drupal::state()->set('siteapikey',$form_state->getValue('site_api_key'));
  if($form_state->getValue('site_api_key') != ''){
    drupal_get_messages('');
    drupal_set_message(t('The Site API Key has been saved with '.$form_state->getValue('site_api_key').''), 'status');
  }
}